import { Project } from './types';

export const projects: Project[] = [
    {
        title: 'Arcade Loyalty Demo',
        slug: 'arcade-loyalty',
        oneLiner: 'Tokenized loyalty backend that tracks lifetime, active, and spendable points',
        role: 'Product & Dev',
        timeframe: '2024–2025',
        stack: ['Node.js', 'TypeScript', 'Express', 'SQLite', 'Base'],
        summary: 'Built a tokenized loyalty backend that mirrors point balances to an ERC-20-style token on Base. The system tracks lifetime, active, and spendable points with full transactional integrity.',
        highlights: [
            'Designed the data model and API around venues, staff roles, and checkouts',
            'Implemented earn/redeem logic with transactional integrity and a blockchain adapter',
            'Built demo flows for sales and partners to showcase real-world usage',
            'Created seamless integration between traditional point systems and on-chain tokens',
        ],
        link: 'https://github.com/yourusername/arcade-loyalty',
        type: 'web3',
    },
    {
        title: 'Bamboo on Base',
        slug: 'bamboo-on-base',
        oneLiner: 'A phased memecoin + on-chain casino ecosystem on Base with quests and playful Web3 UX',
        role: 'Product & Concept',
        timeframe: '2025–ongoing',
        stack: ['Base L2', 'Solidity', 'Viem', 'Next.js'],
        summary: 'A memecoin project evolving into an on-chain casino ecosystem built on Base. Combines playful Web3 UX with quests and gamification.',
        highlights: [
            'Designed phased rollout strategy for memecoin launch',
            'Created on-chain game mechanics and quest system',
            'Built playful, engaging Web3 user experience',
            'Integrated Base L2 for low-cost transactions',
        ],
        link: 'https://github.com/yourusername/bamboo-on-base',
        type: 'web3',
    },
    {
        title: 'Poker Companion',
        slug: 'poker-companion',
        oneLiner: 'A home-game poker dealer assistant PWA with hand evaluation and tournament tools',
        role: 'Product & Dev',
        timeframe: '2025–ongoing',
        stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Zustand', 'Framer Motion'],
        summary: 'Progressive Web App designed to assist home poker game dealers. Features hand evaluation, tournament management, and offline support for seamless gameplay.',
        highlights: [
            'Built mobile-first PWA with offline capabilities',
            'Implemented poker hand evaluation engine',
            'Created tournament timer and blind management system',
            'Designed intuitive interface for fast-paced game flow',
        ],
        link: 'https://github.com/yourusername/poker-companion',
        type: 'web2',
    },
];
